export enum EType {
  reset = 'reset',
  valid = 'valid',
  name = 'name',
  cardImage = 'cardImage',
  cardImageUrl = 'cardImageUrl',
  headerImage = 'headerImage',
  headerImageUrl = 'headerImageUrl',
  title = 'title',
  infoImage = 'infoImage',
  infoImageUrl = 'infoImageUrl',
  infoTitle = 'infoTitle',
  infoHeader = 'infoHeader',
  infoListTitle = 'infoListTitle',
  sliderImage = 'sliderImage',
  sliderImageUrl = 'sliderImageUrl',
  paragraphs = 'paragraphs',
  infoListItems = 'infoListItems',
  infoParagraphs = 'infoParagraphs',
}
