export enum EType {
  reset = 'reset',
  name = 'name',
  cardImage = 'cardImage',
  cardImageUrl = 'cardImageUrl',
  headerImage = 'headerImage',
  headerImageUrl = 'headerImageUrl',
  title = 'title',
  infoImage = 'infoImage',
  infoImageUrl = 'infoImageUrl',
  infoTitle = 'infoTitle',
  infoHeader = 'infoHeader',
  infoListTitle = 'infoListTitle',
  opinionTitle = 'opinionTitle',
  opinionListTitle = 'opinionListTitle',
  opinionName = 'opinionName',
  opinionPhone = 'opinionPhone',
  opinionFax = 'opinionFax',
  opinionEmail = 'opinionEmail',
  opinionImage = 'opinionImage',
  opinionImageUrl = 'opinionImageUrl',
  sliderImage = 'sliderImage',
  sliderImageUrl = 'sliderImageUrl',
}
